project:
  type: website
  output-dir: ../../docs
  render:
    - "*.qmd"
    - "!scratch/"

website:
  title: "Media Coverage of Prosecutors and Their Elections: Results of a Pilot Study"
  sidebar:
    style: "floating"
    search: true
    contents:
      - index.qmd
      - coverage_amount.qmd
      - coverage_content.qmd

format:
  html:
    toc: true


